### ISSUE TITLE
Background correction error

### ISSUE THREAD

**Issue by sschepanski** [ebecht/infinityFlow#3]
Hey Etienne, 
currently, we are trying to analyze the data that we acquired with the InfinityFlow pipeline.
I tried everything to hunt down the error but I still receive it:
_Background correcting
Fehler in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
  0 (non-NA) cases_

Do you have an idea where the error might come from?

Much appreciated,
Steven

**Comment by ebecht** [comment]
Hi Steven,

I think this usually happens if the "Isotype" of one of the antibodies does not match any of the "targets" (because we need the isotype to be measured somewhere for background correction).

Can you check `isotypes[!isotypes %in% targets]` ? If it returns anything that's probably the source of your problem. There can be hard to detect errors (like dashes that are different characters or some blank characters at the end of the strings...).

Hopefully this helps! Please let me know otherwise
Etienne

**Comment by sschepanski** [comment]
Hey Etienne,
it worked! Thanks for your support! :-)

Very much appreciated,
Steven

**Comment by ebecht** [comment]
Glad to hear it worked. I'll make sure to add a check to detect these errors more explicitly.

I'm closing the issue but feel free to reopen or start another one if needed!

Best,
Etienne
